### ISSUE TITLE
Struct properties generated as vars

### ISSUE THREAD

**Issue by JanC** [kean/CreateAPI#16]
Hi @kean 

first, thanks for a lot for this open source project 🙏 

I noticed that all properties of structs are generated as `var`.  From the code I see that the  `isReadonly` rules whether a property is a `var` or a `let`.

https://github.com/kean/CreateAPI/blob/303aecad0969368de29bcd69566f102f0cdf622b/Sources/CreateAPI/Generator/Templates.swift#L407

However, the value of `isReadonly` comes from here so all structs will have their properties as `var`
https://github.com/kean/CreateAPI/blob/303aecad0969368de29bcd69566f102f0cdf622b/Sources/CreateAPI/Generator/Generator%2BRender.swift#L32-L37

I think this could be improved by having a dedicated `options.entities.mutableProperties` option  for it, wdyt?

**Comment by kean** [comment]
Hi. Yeah, I had no time to build it, but it'd be a nice addition.

**Comment by JanC** [comment]
If you agree with the approach, I can create a PR.

**Comment by kean** [comment]
Yes, I think it's fine. It would be nice to add more granular options too, but that's a good starting point.

**Comment by JanC** [comment]
awesome, thanks!
