### ISSUE TITLE
Unstable dependencies

### ISSUE THREAD

**Issue by onmyway133** [kean/CreateAPI#23]
Hi Alex, first of all thanks for creating this great tool.

I've successfully generated Appstore Connect APIs using your tool at https://github.com/onmyway133/AppStoreConnect
And I'm ready to include it into https://github.com/onmyway133/Swiftlane. However, Xcode complains about `urlqueryencoder` being unstable dependencies.

> Dependencies could not be resolved because root depends on 'AppStoreConnect' 0.0.2..<1.0.0.
'AppStoreConnect' >= 0.0.2 cannot be used because no versions of 'AppStoreConnect' match the requirement 0.0.3..<1.0.0 and package 'appstoreconnect' is required using a stable-version but 'appstoreconnect' depends on an unstable-version package 'urlqueryencoder'.

I guess in the generated Package.swift, we need to specify `from` instead of `branch`?

```
.package(url: "https://github.com/kean/URLQueryEncoder", from: "0.2.0"),
```

**Comment by kean** [comment]
I think so. Updated in the `main` branch.

**Comment by onmyway133** [comment]
Thank you 👍
