### ISSUE TITLE
Is there any plans to add support for adding prefix and suffix for entities?

### ISSUE THREAD

**Issue by imjn** [kean/CreateAPI#3]
Hello Hello. I have a question.
Are there any plans to add support for adding prefix and suffix for generated entities like [SwagGen](https://github.com/yonaskolb/SwagGen) does?

I have an existing project that I want to try to implement this tool and replace some entities at first and gradually replace all the entities hardcoded with the generated ones. In this case, prefix and suffix help me to integrate the generated entities easier.

If adding the feature is suited for the direction this tool is going, I am happy to make a PR for that :)

**Comment by kean** [comment]
Yes, I'm open to adding as many customization options as needed. This sounds like a useful thing to add.

**Comment by imjn** [comment]
Thank you.

> It'll be also nice to have a option to add a "namespace" for generated entities.

Yes, that is true. This option is exactly the one that I am using right now.

But prefix and suffix also can be helpful so I'll open a PR for that in the near future :)

I got an answer so I close this issue.

**Comment by JanC** [comment]
👋 
I'm just browsing the issues to see what have already beed discussed.

> It'll be also nice to have a option to add a "namespace" for generated entities.

This is something that would be useful indeed
