### ISSUE TITLE
Can't run using Mint

### ISSUE THREAD

**Issue by denizdogan** [kean/CreateAPI#9]
```
$ mint install kean/CreateAPI
🌱 Finding latest version of CreateAPI
🌱 Cloning CreateAPI 0.0.1
🌱 Resolving package
🌱  Executable product not found in CreateAPI 0.0.1
$ mint run CreateAPI create-api generate -h
🌱  "CreateAPI" package not found
```

Are you planning on making a new release soon?

**Comment by simorgh3196** [comment]
Unfortunately, it hasn't been released yet.

If you want to use it before a new release is available, you can use `Mint` by specifying the `main` branch.

```shell
mint install kean/CreateAPI@main
```

**Comment by kean** [comment]
I pushed a new release – [0.0.2](https://github.com/kean/CreateAPI/releases/tag/0.0.2)
